databases:
  - name: party-sync-db
    databaseName: party_sync_db
    user: party_sync_user
    plan: free

services:
  - type: web
    name: party-sync-watch
    env: node
    plan: free
    buildCommand: npm install && npx prisma generate && npm run build
    startCommand: npm start
    healthCheckPath: /
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        fromDatabase:
          name: party-sync-db
          property: connectionString
      - key: RENDER_EXTERNAL_URL
        sync: false